"""
This type stub file was generated by pyright.
"""

import os
import sys
import weakref
from concurrent.futures import Future
from .exc import DeviceError
from .serinterface import BuildHAT

"""Functionality for handling Build HAT devices"""
class Device:
    """Creates a single instance of the buildhat for all devices to use"""
    _instance = ...
    _started = ...
    _device_names = ...
    _used = ...
    UNKNOWN_DEVICE = ...
    DISCONNECTED_DEVICE = ...
    def __init__(self, port) -> None:
        """Initialise device

        :param port: Port of device
        :raises DeviceError: Occurs if incorrect port specified or port already used
        """
        ...
    
    def __del__(self): # -> None:
        """Handle deletion of device"""
        ...
    
    @staticmethod
    def name_for_id(typeid): # -> str:
        """Translate integer type id to device name (python class)

        :param typeid: Type of device
        :return: Name of device
        """
        ...
    
    @staticmethod
    def desc_for_id(typeid): # -> str:
        """Translate integer type id to something more descriptive than the device name

        :param typeid: Type of device
        :return: Description of device
        """
        ...
    
    @property
    def connected(self):
        """Whether device is connected or not

        :return: Connection status
        """
        ...
    
    @property
    def typeid(self):
        """Type ID of device

        :return: Type ID
        """
        ...
    
    @property
    def typeidcur(self):
        """Type ID currently present

        :return: Type ID
        """
        ...
    
    @property
    def name(self): # -> str:
        """Determine name of device on port

        :return: Device name
        """
        ...
    
    @property
    def description(self): # -> str:
        """Device on port info

        :return: Device description
        """
        ...
    
    def isconnected(self): # -> None:
        """Whether it is connected or not

        :raises DeviceError: Occurs if device no longer the same
        """
        ...
    
    def reverse(self): # -> None:
        """Reverse polarity"""
        ...
    
    def get(self):
        """Extract information from device

        :return: Data from device
        :raises DeviceError: Occurs if device not in valid mode
        """
        ...
    
    def mode(self, modev): # -> None:
        """Set combimode or simple mode

        :param modev: List of tuples for a combimode, or integer for simple mode
        """
        ...
    
    def select(self): # -> None:
        """Request data from mode

        :raises DeviceError: Occurs if device not in valid mode
        """
        ...
    
    def on(self): # -> None:
        """Turn on sensor"""
        ...
    
    def off(self): # -> None:
        """Turn off sensor"""
        ...
    
    def deselect(self): # -> None:
        """Unselect data from mode"""
        ...
    
    def callback(self, func): # -> None:
        """Set callback function

        :param func: Callback function
        """
        ...
    
    @property
    def interval(self): # -> int:
        """Interval between data points in milliseconds

        :getter: Gets interval
        :setter: Sets interval
        :return: Device interval
        :rtype: int
        """
        ...
    
    @interval.setter
    def interval(self, value): # -> None:
        """Interval between data points in milliseconds

        :param value: Interval
        :type value: int
        :raises DeviceError: Occurs if invalid interval passed
        """
        ...
    


