"""
This type stub file was generated by pyright.
"""

import sys
import time
import math
from grove.gpio import GPIO
from gpiozero import DigitalInputDevice, HoldMixin, SmoothedInputDevice
from grove.adc import ADC
from ctypes import *
from ctypes import util
from grove.i2c import Bus

usleep = ...
_TIMEOUT1 = ...
_TIMEOUT2 = ...
class UltrasonicSensor:
    def __init__(self, pin) -> None:
        ...
    
    @property
    def getDist(self): # -> float | None:
        ...
    


class LineFinder(SmoothedInputDevice):
    """
    Extends :class:`SmoothedInputDevice` and represents a single pin line
    sensor like the TCRT5000 infra-red proximity sensor found in the `CamJam #3
    EduKit`_.

    A typical line sensor has a small circuit board with three pins: VCC, GND,
    and OUT. VCC should be connected to a 3V3 pin, GND to one of the ground
    pins, and finally OUT to the GPIO specified as the value of the *pin*
    parameter in the constructor.

    The following code will print a line of text indicating when the sensor
    detects a line, or stops detecting a line::

        from gpiozero import LineSensor
        from signal import pause

        sensor = LineSensor(4)
        sensor.when_line = lambda: print('Line detected')
        sensor.when_no_line = lambda: print('No line detected')
        pause()

    :type pin: int or str
    :param pin:
        The GPIO pin which the sensor is connected to. See :ref:`pin-numbering`
        for valid pin numbers. If this is :data:`None` a :exc:`GPIODeviceError`
        will be raised.

    :type pull_up: bool or None
    :param pull_up:
        See description under :class:`InputDevice` for more information.

    :type active_state: bool or None
    :param active_state:
        See description under :class:`InputDevice` for more information.

    :param int queue_len:
        The length of the queue used to store values read from the sensor. This
        defaults to 5.

    :param float sample_rate:
        The number of values to read from the device (and append to the
        internal queue) per second. Defaults to 100.

    :param float threshold:
        Defaults to 0.5. When the average of all values in the internal queue
        rises above this value, the sensor will be considered "active" by the
        :attr:`~SmoothedInputDevice.is_active` property, and all appropriate
        events will be fired.

    :param bool partial:
        When :data:`False` (the default), the object will not return a value
        for :attr:`~SmoothedInputDevice.is_active` until the internal queue has
        filled with values.  Only set this to :data:`True` if you require
        values immediately after object construction.

    :type pin_factory: Factory or None
    :param pin_factory:
        See :doc:`api_pins` for more information (this is an advanced feature
        which most users can ignore).

    .. _CamJam #3 EduKit: http://camjam.me/?page_id=1035
    """
    def __init__(self, pin=..., *, pull_up=..., active_state=..., queue_len=..., sample_rate=..., threshold=..., partial=..., pin_factory=...) -> None:
        ...
    
    @property
    def value(self): # -> object | float:
        """
        Returns a value representing the average of the queued values. This
        is 0 for black under the sensor, and 1 for white under
        the sensor.
        """
        ...
    
    @property
    def line_detected(self): # -> bool:
        ...
    


class LightSensor:
    '''
    Grove Light Sensor class

    Args:
        pin(int): number of analog pin/channel the sensor connected.
    '''
    def __init__(self, channel) -> None:
        ...
    
    @property
    def light(self): # -> Any:
        '''
        Get the light strength value, maximum value is 100.0%

        Returns:
            (int): ratio, 0(0.0%) - 1000(100.0%)
        '''
        ...
    


class IRSensor:
    '''
    IR Sensor class

    Args:
        pin(int): number of the analog pin the sensor is connected to.
    '''
    def __init__(self, channel1, channel2) -> None:
        ...
    
    @property
    def value1(self): # -> Any:
        '''
        Get the infrared strength value, maximum value is 999

        Returns:
            (int): ratio, 0 - 999
        '''
        ...
    
    @property
    def value2(self): # -> Any:
        '''
        Get the infrared strength value, maximum value is 999

        Returns:
            (int): ratio, 0 - 999
        '''
        ...
    


ICM20600_I2C_ADDR0 = ...
ICM20600_I2C_ADDR1 = ...
__c_module = ...
_ = ...
_akicm = ...
class ICM20600Cfg(Structure):
    _fields_ = ...


class GroveIMU9DOFICM20600:
    def __init__(self, addr=...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def get_temperature(self): # -> float:
        ...
    
    def get_accel(self): # -> tuple[float, float, float]:
        ...
    
    def get_gyro(self): # -> tuple[float, float, float]:
        ...
    
    temperature = ...


AK09918_I2C_ADDR = ...
AK09918_POWER_DOWN = ...
AK09918_NORMAL = ...
AK09918_CONTINUOUS_10HZ = ...
AK09918_CONTINUOUS_20HZ = ...
AK09918_CONTINUOUS_50HZ = ...
AK09918_CONTINUOUS_100HZ = ...
AK09918_SELF_TEST = ...
AK09918_ERR_OK = ...
AK09918_ERR_DOR = ...
AK09918_ERR_NOT_RDY = ...
AK09918_ERR_TIMEOUT = ...
AK09918_ERR_SELFTEST_FAILED = ...
AK09918_ERR_OVERFLOW = ...
AK09918_ERR_WRITE_FAILED = ...
AK09918_ERR_READ_FAILED = ...
class GroveIMU9DOFAK09918:
    def __init__(self, addr=...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def mode(self, mode=...): # -> Any:
        ...
    
    def reset(self): # -> Any:
        ...
    
    def is_ready(self): # -> bool:
        ...
    
    def is_skip(self): # -> Any:
        ...
    
    def get_magnet(self): # -> tuple[float, float, float]:
        ...
    
    def get_magnet_raw(self): # -> tuple[float, float, float]:
        ...
    
    def err_string(self, errval): # -> Any:
        ...
    


class IMUSensor:
    def __init__(self) -> None:
        ...
    
    def getAccel(self): # -> tuple[float, ...]:
        ...
    
    def getGyro(self): # -> tuple[float, float, float]:
        ...
    
    def getMag(self): # -> tuple[float, float, float]:
        ...
    


class Button(HoldMixin, DigitalInputDevice):
    """
    Extends :class:`DigitalInputDevice` and represents a simple push button
    or switch.

    Connect one side of the button to a ground pin, and the other to any GPIO
    pin. Alternatively, connect one side of the button to the 3V3 pin, and the
    other to any GPIO pin, then set *pull_up* to :data:`False` in the
    :class:`Button` constructor.

    The following example will print a line of text when the button is pushed::

        from gpiozero import Button

        button = Button(4)
        button.wait_for_press()
        print("The button was pressed!")

    :type pin: int or str
    :param pin:
        The GPIO pin which the button is connected to. See :ref:`pin-numbering`
        for valid pin numbers. If this is :data:`None` a :exc:`GPIODeviceError`
        will be raised.

    :type pull_up: bool or None
    :param pull_up:
        If :data:`True` (the default), the GPIO pin will be pulled high by
        default.  In this case, connect the other side of the button to ground.
        If :data:`False`, the GPIO pin will be pulled low by default. In this
        case, connect the other side of the button to 3V3. If :data:`None`, the
        pin will be floating, so it must be externally pulled up or down and
        the ``active_state`` parameter must be set accordingly.

    :type active_state: bool or None
    :param active_state:
        See description under :class:`InputDevice` for more information.

    :type bounce_time: float or None
    :param bounce_time:
        If :data:`None` (the default), no software bounce compensation will be
        performed. Otherwise, this is the length of time (in seconds) that the
        component will ignore changes in state after an initial change.

    :param float hold_time:
        The length of time (in seconds) to wait after the button is pushed,
        until executing the :attr:`when_held` handler. Defaults to ``1``.

    :param bool hold_repeat:
        If :data:`True`, the :attr:`when_held` handler will be repeatedly
        executed as long as the device remains active, every *hold_time*
        seconds. If :data:`False` (the default) the :attr:`when_held` handler
        will be only be executed once per hold.

    :type pin_factory: Factory or None
    :param pin_factory:
        See :doc:`api_pins` for more information (this is an advanced feature
        which most users can ignore).
    """
    def __init__(self, pin=..., *, pull_up=..., active_state=..., bounce_time=..., hold_time=..., hold_repeat=..., pin_factory=...) -> None:
        ...
    
    @property
    def value(self): # -> int:
        """
        Returns 1 if the button is currently pressed, and 0 if it is not.
        """
        ...
    


class HallSensor(HoldMixin, DigitalInputDevice):
    """
    Simple Hall Sensor Class

    Args:
        pin(int): the digital pin to which the sensor is assigned
        pull_up(bool): whether the sensor is set to pull up or down. This impacts whether the 
            sensor returns a 0 or 1 when near a magnet and must be set to false for the wiring 
            setup of the base hat.
        bounce_time(float): The length of time (in seconds) after the button is presse during which 
            new inputs are ignored. This minimizeds 'bouncy' signals, where the output of the button
            changes rapidly as it is being pressed. The base time for this is 1 second.
   
    """
    def __init__(self, pin=..., *, pull_up=..., active_state=..., bounce_time=..., pin_factory=...) -> None:
        ...
    
    @property
    def value(self): # -> int:
        """
        Returns 1 if the button is currently pressed, and 0 if it is not.
        """
        ...
    


