"""
This type stub file was generated by pyright.
"""

from .devices import Device

"""Color sensor handling functionality"""
class ColorSensor(Device):
    """Color sensor

    :param port: Port of device
    :raises DeviceError: Occurs if there is no color sensor attached to port
    """
    def __init__(self, port) -> None:
        """
        Initialise color sensor

        :param port: Port of device
        """
        ...
    
    def segment_color(self, r, g, b): # -> str:
        """Return the color name from RGB

        :param r: Red
        :param g: Green
        :param b: Blue
        :return: Name of the color as a string
        :rtype: str
        """
        ...
    
    def rgb_to_hsv(self, r, g, b): # -> tuple[int, int, int]:
        """Convert RGB to HSV

        Based on https://www.rapidtables.com/convert/color/rgb-to-hsv.html algorithm

        :param r: Red
        :param g: Green
        :param b: Blue
        :return: HSV representation of color
        :rtype: tuple
        """
        ...
    
    def get_color(self): # -> str:
        """Return the color

        :return: Name of the color as a string
        :rtype: str
        """
        ...
    
    def get_ambient_light(self): # -> int:
        """Return the ambient light

        :return: Ambient light
        :rtype: int
        """
        ...
    
    def get_reflected_light(self): # -> int:
        """Return the reflected light

        :return: Reflected light
        :rtype: int
        """
        ...
    
    def get_color_rgbi(self): # -> list[Any]:
        """Return the color

        :return: RGBI representation
        :rtype: list
        """
        ...
    
    def get_color_hsv(self): # -> tuple[int, int, int]:
        """Return the color

        :return: HSV representation
        :rtype: tuple
        """
        ...
    
    def wait_until_color(self, color): # -> None:
        """Wait until specific color

        :param color: Color to look for
        """
        ...
    
    def wait_for_new_color(self): # -> str:
        """Wait for new color or returns immediately if first call

        :return: Name of the color as a string
        :rtype: str
        """
        ...
    
    def on(self): # -> None:
        """Turn on the sensor and LED"""
        ...
    


