"""
This type stub file was generated by pyright.
"""

"""HAT handling functionality"""
class Hat:
    """Allows enumeration of devices which are connected to the hat"""
    def __init__(self, device=..., debug=...) -> None:
        """Hat

        :param device: Optional string containing path to Build HAT serial device
        :param debug: Optional boolean to log debug information
        """
        ...
    
    def get(self): # -> dict[Any, Any]:
        """Get devices which are connected or disconnected

        :return: Dictionary of devices
        :rtype: dict
        """
        ...
    
    def get_logfile(self): # -> str | None:
        """Get the filename of the debug log (If enabled, None otherwise)

        :return: Path of the debug logfile
        :rtype: str or None
        """
        ...
    
    def get_vin(self):
        """Get the voltage present on the input power jack

        :return: Voltage on the input power jack
        :rtype: float
        """
        ...
    
    def set_leds(self, color=...): # -> None:
        """Set the two LEDs on or off on the BuildHAT.

        By default the color depends on the input voltage with green being nominal at around 8V
        (The fastest time the LEDs can be perceptually toggled is around 0.025 seconds)

        :param color: orange, green, both, off, or voltage (default)
        """
        ...
    
    def orange_led(self, status=...): # -> None:
        """Turn the BuildHAT's orange LED on or off

        :param status: True to turn it on, False to turn it off
        """
        ...
    
    def green_led(self, status=...): # -> None:
        """Turn the BuildHAT's green LED on or off

        :param status: True to turn it on, False to turn it off
        """
        ...
    


