"""
This type stub file was generated by pyright.
"""

from enum import Enum
from .devices import Device

'''
Lego Motor:
    Description:
        This code can be used to run either type of Spike motor. This includes accessing data 
        from the encoder, such as the motor position and speed, as well as setting the motor to
        run. Functionality includes setting the motor power, the motor speed, or even the motor
        position.

    Hardware:
        These motors can be connected to any of the BuildHAT motor ports. The letter associated 
        with each port can be seen just behind the ports, going from A to D counterclockwise.
        
        More info:
        https://www.raspberrypi.com/documentation/accessories/build-hat.html
    
    Initialization:
        motor_name = Motor('port')

        If you plug your motor into port A and want to name it 'left_motor', your initializaion
        will look like this:

        left_motor = Motor('A')

    Motor.start(speed (optional)):
        This function can be used to begin running a motor. The speed, ranging from -100 to 100,
        can be set here, but if not input is given it will use default_speed.

    Motor.stop()
        This function stops the motor, setting its speed to 0.
        
    Motor.run_PID(Kp, Ki, Kd, windup, speed(optional))
        This function runs the motor using a PID controller to keep the speed at a desired value.
        Without a speed input, the motor will use default_speed. PID values for start are .003, 
        .01, and 0, respectively. The windup defines the maximum value from the integral gain,
        typically 100.
        
    Motor.pwm(speed)
        This function takes an input from -1 to 1 and feeds this to the motor as a square wave with
        constant frequency and duty cycle given as the speed input. This effectively allows for 
        direct control of the motor force.
        
    Motor.set_default_speed(default_speed):
        This function can be used to set the default speed of the motor, ranging from -100 
        to 100 as a proportion of the maximum speed of the motor. This is automatically set 
        to 20.

    Motor.run_for_rotations(rotations, speed (optional), blocking (optional)):
        This function can be used to run the motor for a set number of revolutions. The speed,
        ranging from -100 to 100, can be set here, but if no input is given it will use 
        default_speed. One can also set whether this function has blocking. This is a 
        boolean value which is true if it is not set at the function call. While true,
        blocking is enabled, meaning that the next line of code will not be run until
        the motor has finished running for the required number of rotations. If blocking 
        is false, the next line of code will immediately be run while the motor is 
        turning.

    Motor.run_for_degrees(degrees, speed (optional), blocking (optional)):
        This function can be used to run the motor for a set number of degrees. The speed,
        ranging from -100 to 100, can be set here, but if no input is given it will use 
        default_speed. One can also set whether this function has blocking. This is a 
        boolean value which is true if it is not set at the function call. While true,
        blocking is enabled, meaning that the next line of code will not be run until
        the motor has finished running for the required number of degrees. If blocking 
        is false, the next line of code will immediately be run while the motor is 
        turning.

    Motor.run_to_position(degrees, speed (optional), blocking (optional), direction (optional)):
        This function can be used to run the motor to a set position in degrees, ranging from -180 
        to 180. The speed, ranging from -100 to 100, can be set here, but if no input is given it 
        will use default_speed. The direction taken by the motor can also be set, with 'shortest'
        as the default and 'clockwise' and 'anticlockwise' being other options. One can also set 
        whether this function has blocking. This is a boolean value which is true if it is not 
        set at the function call. While true, blocking is enabled, meaning that the next line of 
        code will not be run until the motor has finished running to the desired position. If 
        blocking is false, the next line of code will immediately be run while the motor is 
        turning.

    Motor.run_for_seconds(seconds, speed(optional), blocking(optional)):
        This function can be used to run the motor for a set length of time. The speed,
        ranging from -100 to 100, can be set here, but if no input is given it will use 
        default_speed. One can also set whether this function has blocking. This is a 
        boolean value which is true if it is not set at the function call. While true,
        blocking is enabled, meaning that the next line of code will not be run until
        the motor has finished running for the required number of seconds. If blocking 
        is false, the next line of code will immediately be run while the motor is 
        turning.

    Motor.get_position():
        Returns the current position of the motor, in degrees, relative to some starting position.
        This can be either positive or negative and is not limited in value. 
    
    Motor.get_apostition():
        Returns the current absolute position of the motors, in degrees, in terms of a single rotation. 
        This can be positive or negative but is restricted to be between -180 and 180.

    Motor.get_speed():
        Returns the current speed of the motor, ranging from -100 to 100.
    
    EncoderExamples.py and Run_Examples.py: 
        Usage of this code is demonstrated in the example files for these motors in the Examples
        folder on your Pi's desktop.

'''
class Motor(Device):
    """Motor device

    :param port: Port of device
    :raises DeviceError: Occurs if there is no motor attached to port
    """
    def __init__(self, port) -> None:
        """Initialise motor

        :param port: Port of device
        """
        ...
    
    def run_PID(self, Kp, Ki, Kd, windup, speed=...): # -> None:
        ...
    
    def start(self, speed=...): # -> None:
        """Start motor

        :param speed: Speed ranging from -100 to 100
        :raises MotorError: Occurs when invalid speed specified
        """
        ...
    
    def stop(self): # -> None:
        """Stop motor"""
        ...
    
    def set_default_speed(self, default_speed): # -> None:
        """Set the default speed of the motor

        :param default_speed: Speed ranging from -100 to 100
        :raises MotorError: Occurs if invalid speed passed
        """
        ...
    
    def run_for_rotations(self, rotations, speed=..., blocking=...): # -> None:
        """Run motor for N rotations

        :param rotations: Number of rotations
        :param speed: Speed ranging from -100 to 100
        :param blocking: Whether call should block till finished
        :raises MotorError: Occurs if invalid speed passed
        """
        ...
    
    def run_for_degrees(self, degrees, speed=..., blocking=...): # -> None:
        """Run motor for N degrees

        Speed of 1 means 1 revolution / second

        :param degrees: Number of degrees to rotate
        :param speed: Speed ranging from -100 to 100
        :param blocking: Whether call should block till finished
        :raises MotorError: Occurs if invalid speed passed
        """
        ...
    
    def run_to_position(self, degrees, speed=..., blocking=..., direction=...): # -> None:
        """Run motor to position (in degrees)

        :param degrees: Position in degrees from -180 to 180
        :param speed: Speed ranging from 0 to 100
        :param blocking: Whether call should block till finished
        :param direction: shortest (default)/clockwise/anticlockwise
        :raises MotorError: Occurs if invalid speed or angle passed
        """
        ...
    
    def run_for_seconds(self, seconds, speed=..., blocking=...): # -> None:
        """Run motor for N seconds

        :param seconds: Time in seconds
        :param speed: Speed ranging from -100 to 100
        :param blocking: Whether call should block till finished
        :raises MotorError: Occurs when invalid speed specified
        """
        ...
    
    def pwmparams(self, pwmthresh, minpwm): # -> None:
        """PWM thresholds

        :param pwmthresh: Value 0 to 1, threshold below, will switch from fast to slow, PWM
        :param minpwm: Value 0 to 1, threshold below which it switches off the drive altogether
        :raises MotorError: Occurs if invalid values are passed
        """
        ...
    
    def pwm(self, pwmv): # -> None:
        """PWM motor

        :param pwmv: Value -1 to 1
        :raises MotorError: Occurs if invalid pwm value passed
        """
        ...
    
    def get_position(self):
        """Get position of motor with relation to preset position (can be negative or positive)

        :return: Position of motor in degrees from preset position
        :rtype: int
        """
        ...
    
    def get_aposition(self):
        """Get absolute position of motor

        :return: Absolute position of motor from -180 to 180
        :rtype: int
        """
        ...
    
    def get_speed(self):
        """Get speed of motor

        :return: Speed of motor
        :rtype: int
        """
        ...
    
    def plimit(self, plimit): # -> None:
        """Limit power

        :param plimit: Value 0 to 1
        :raises MotorError: Occurs if invalid plimit value passed
        """
        ...
    
    def coast(self): # -> None:
        """Coast motor"""
        ...
    
    def float(self): # -> None:
        """Float motor"""
        ...
    
    @property
    def release(self): # -> bool:
        """Determine if motor is released after running, so can be turned by hand

        :getter: Returns whether motor is released, so can be turned by hand
        :setter: Sets whether motor is released, so can be turned by hand
        :return: Whether motor is released, so can be turned by hand
        :rtype: bool
        """
        ...
    
    @release.setter
    def release(self, value): # -> None:
        """Determine if the motor is released after running, so can be turned by hand

        :param value: Whether motor should be released, so can be turned by hand
        :type value: bool
        """
        ...
    
    @property
    def when_rotated(self):
        """
        Handle rotation events

        :getter: Returns function to be called when rotated
        :setter: Sets function to be called when rotated
        :return: Callback function
        """
        ...
    
    @when_rotated.setter
    def when_rotated(self, value): # -> None:
        """Call back, when motor has been rotated

        :param value: Callback function
        """
        ...
    
    def bias(self, bias):
        """Bias motor

        :param bias: Value 0 to 1
        :raises MotorError: Occurs if invalid bias value passed

        .. deprecated:: 0.6.0
        """
        ...
    


class MotorRunmode(Enum):
    """Current mode motor is in"""
    NONE = ...
    FREE = ...
    DEGREES = ...
    SECONDS = ...


