"""
This type stub file was generated by pyright.
"""

from enum import Enum

"""Build HAT handling functionality"""
class HatState(Enum):
    """Current state that hat is in"""
    OTHER = ...
    FIRMWARE = ...
    NEEDNEWFIRMWARE = ...
    BOOTLOADER = ...


class Connection:
    """Connection information for a port"""
    def __init__(self) -> None:
        """Initialise connection"""
        ...
    
    def update(self, typeid, connected, callit=...): # -> None:
        """Update connection information for port

        :param typeid: Type ID of device on port
        :param connected: Whether device is connected or not
        :param callit: Callback function
        """
        ...
    


def cmp(str1, str2):
    """Look for str2 in str1

    :param str1: String to look in
    :param str2: String to look for
    :return: Whether str2 exists
    """
    ...

class BuildHAT:
    """Interacts with Build HAT via UART interface"""
    CONNECTED = ...
    CONNECTEDPASSIVE = ...
    DISCONNECTED = ...
    DEVTIMEOUT = ...
    NOTCONNECTED = ...
    PULSEDONE = ...
    RAMPDONE = ...
    FIRMWARE = ...
    BOOTLOADER = ...
    DONE = ...
    PROMPT = ...
    RESET_GPIO_NUMBER = ...
    BOOT0_GPIO_NUMBER = ...
    def __init__(self, firmware, signature, version, device=..., debug=...) -> None:
        """Interact with Build HAT

        :param firmware: Firmware file
        :param signature: Signature file
        :param version: Firmware version
        :param device: Serial device to use
        :param debug: Optional boolean to log debug information
        :raises BuildHATError: Occurs if can't find HAT
        """
        ...
    
    def resethat(self): # -> None:
        """Reset the HAT"""
        ...
    
    def loadfirmware(self, firmware, signature): # -> None:
        """Load firmware

        :param firmware: Firmware to load
        :param signature: Signature to load
        """
        ...
    
    def getprompt(self): # -> None:
        """Loop until prompt is found

        Need to decide what we will do, when no prompt
        """
        ...
    
    def checksum(self, data): # -> Literal[1]:
        """Calculate checksum from data

        :param data: Data to calculate the checksum from
        :return: Checksum that has been calculated
        """
        ...
    
    def write(self, data, log=..., replace=...): # -> None:
        """Write data to the serial port of Build HAT

        :param data: Data to write to Build HAT
        :param log: Whether to log line or not
        :param replace: Whether to log an alternative string
        """
        ...
    
    def read(self): # -> str:
        """Read data from the serial port of Build HAT

        :return: Line that has been read
        """
        ...
    
    def shutdown(self): # -> None:
        """Turn off the Build HAT devices"""
        ...
    
    def motorloop(self, q): # -> None:
        """Event handling for non-blocking motor commands

        :param q: Queue of motor functions
        """
        ...
    
    def callbackloop(self, q): # -> None:
        """Event handling for callbacks

        :param q: Queue of callback events
        """
        ...
    
    def loop(self, cond, uselist, q, listevt):
        """Event handling for Build HAT

        :param cond: Condition used to block user's script till we're ready
        :param uselist: Whether we're using the HATs 'list' function or not
        :param q: Queue for callback events
        """
        ...
    


