"""
This type stub file was generated by pyright.
"""

import sys
import os as osm
import time

'''
provide functions to promote process real-time priority or change back to default

## License

The MIT License (MIT)

Grove Base Hat for the Raspberry Pi, used to connect grove sensors.
Copyright (C) 2018  Seeed Technology Co.,Ltd. 

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
'''
SCHED_OTHER = ...
SCHED_FIFO = ...
SCHED_RR = ...
SCHED_BATCH = ...
SCHED_IDLE = ...
_os_import = ...
max_param = ...
if sys.version_info >= (3, 3):
    max_priority = ...
    max_param = ...
    norm_param = ...
else:
    ...
if not max_param and _os_import:
    class _sched_param(ctypes.Structure):
        _fields_ = ...
    
    
    max_param_c = ...
    max_priority = ...
    max_param = ...
    norm_param_c = ...
    norm_param = ...
def set_max_priority(): # -> Literal[False] | None:
    "Set current process to highest priority"
    ...

def set_default_priority(): # -> Literal[False] | None:
    "Set current process to default priority"
    ...

if __name__ == '__main__':
    ...
